apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    worker_processes auto;
    events {
      worker_connections 1024;
    }
    http {
      upstream flask-app-service {
        server flask-app-service:5000;
      }
      server {
         listen 443 ssl;
         server_name localhost;
    
         ssl_certificate /etc/nginx/ssl/tls.crt; 
         ssl_certificate_key /etc/nginx/ssl/tls.key;
    
         ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
         ssl_ciphers         HIGH:!aNULL:!MD5;
    
         ssl_session_cache shared:SSL:10m;
         ssl_session_timeout 10m;
    
        location / {
          proxy_pass http://flask-app-service;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
      }
    }